version: '2'
services:
    pcpiezasapp:
        image: pcpiezasapp
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.24.109:6033/pcpiezas
        ports:
            - 8440-8443:8443
   
