version: '2'
services:
    pcpiezasapp:
        image: pcpiezasapp
        environment:
            - SPRING_RABBITMQ_HOST=192.168.24.125
            - SPRING_RABBITMQ_PORT=5672
        ports:
            - 5670-5672:5672
   
